### ISSUE TITLE
EPIC:  First use & Getting Started improvements

### ISSUE THREAD

**Issue by catrobson** [fabric8-ui/fabric8-ux#821]
**REMOVE GETTING STARTED PAGE**
- [ ] Git connect during wizard
- [ ] OSO connect automatically, remove getting started page from flow
- [ ] OSO project check performed in background

**GUIDED TOUR**
- [ ] Initial concepts of guided tour for new users (Bangalore team leading)
